package:
  name: glue-core
  version: {{version}}

{{source}}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - glue = glue.main:main
    - glue-config = glue.config_gen:main
    - glue-deps = glue._deps:main
  osx_is_app: True
  skip: true  # [py27]

requirements:

  build:
    - python
    - setuptools >=30.3
    - setuptools_scm

  run:

    # The following is needed to make sure that the package works as a GUI
    # application (glue needs to be run with python.app, not python)
    - python.app  # [osx]

    # Required dependencies
    - python
    - numpy >=1.9
    - matplotlib >=2.1
    - scipy >=1.0
    - pandas >=0.14
    - astropy >=2.0
    - setuptools >=1.0
    - qtpy >=1.2
    - ipython >=4.0
    - ipykernel >=4.0,!=5.0.0,!=5.1.0
    - qtconsole
    - dill >=0.2
    - xlrd >=1.0
    - h5py >=2.4
    - mpl-scatter-density >=0.5
    - bottleneck >=1.2

    - pyqt >=5.6

    # Optional dependencies (defined in ``extras_require``)
    - scikit-image

    # Temporary: the scikit-image conda package is missing the dask dependency
    # so we add it here for now
    - dask

    # For some reason, when on Windows with Python 2.7, conda tries to install
    # an older version of PyQt5 with sip 4.19 which causes issues
    - sip 4.18.*  # [win and py27]

test:
  imports:
    - glue
    - glue.core
    - glue.app.qt
  commands:
    - glue --version
    - glue-deps list

# NOTE: we deliberatey do NOT include an app entry here, because we instead do this
# in the glueviz meta-package (we don't want glue to appear twice in the navigator)

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
