package:
  name: glue-wwt
  version: {{version}}

{{source}}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python
    - numpy
    - glue-core >=0.15
    - qtpy
    - astropy
    - pywwt >=0.6.0

test:
  imports:
    - glue_wwt

about:
  home: https://github.com/glue-viz/glue-wwt
  license: BSD 3-Clause
  summary: WWT viewer plugin for glue

extra:
  recipe-maintainers:
    - astrofrog
