package:
  name: glue-jupyter
  version: {{version}}

{{source}}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed --no-build-isolation .
  noarch: python

requirements:

  build:
    - python >=3.6
    - setuptools
    - setuptools_scm

  run:
    - python >=3.6
    - glue-core >=0.15
    - glue-vispy-viewers >=0.12
    - notebook
    - ipympl
    - ipyvolume
    - ipywidgets
    - ipymaterialui =0.1.1
    - ipyvuetify >1.0.4,<2
    - bqplot-image-gl
    - bqplot >=0.12

test:
  imports:
    - glue_jupyter

about:
  home: https://github.com/glue-viz/glue-jupyter
  license: BSD 3-Clause
  summary: Jupyter interface to glue

extra:
  recipe-maintainers:
    - astrofrog
