package:
  name: glue-jupyter
  version: {{version}}

{{source}}

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed --no-build-isolation .
  noarch: python

requirements:

  build:
    - python >=3.6
    - setuptools
    - setuptools_scm

  run:
    - python >=3.6
    - glue-core >=1.0
    - glue-vispy-viewers >=1.0
    - notebook >=4.0
    - ipympl >=0.3.0
    - ipyvolume >=0.5.0
    - ipywidgets >=7.4.0
    - ipyvuetify >1.2.0,<2
    - bqplot-image-gl >=1.0.0
    - bqplot >=0.12.17
    - scikit-image

test:
  imports:
    - glue_jupyter

about:
  home: https://github.com/glue-viz/glue-jupyter
  license: BSD 3-Clause
  summary: Jupyter interface to glue

extra:
  recipe-maintainers:
    - astrofrog
