package:
  name: glue-vispy-viewers
  version: {{version}}

{{source}}

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - python >=3.6
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python >=3.6
    - numpy
    - pyopengl
    - glue-core >=1.0
    - qtpy
    - pyqt >=5.9
    - scipy
    - astropy >=4.0
    - pillow
    - matplotlib
    - vispy >=0.6

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD 3-Clause
  summary: 3D viewers for Glue

extra:
  recipe-maintainers:
    - astrofrog
