name: Integration testing

on:
  push:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.os }} ${{ matrix.python }} ${{ matrix.channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.6, 3.7, 3.8, 3.9]
        channel: [conda-forge, glueviz, glueviz/label/dev]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install mamba
      run: conda install -c conda-forge mamba
    - name: Install glueviz with mamba
      run: mamba create -n test-mamba -c ${{ matrix.channel }} python=${{ matrix.python }} "glueviz>=0.999"
    - name: Install glueviz with conda
      run: conda create -n test-conda -c ${{ matrix.channel }} python=${{ matrix.python }} "glueviz>=0.999"
